const services = { transfer: { name: "超渡", slots: ["afternoon"] }, numerology: { name: "生命靈數分析", slots: ["daytime", "evening"] } };
const slots = { afternoon: "下午時段（詳細時間另行確認）", daytime: "假日白天（詳細時間另行確認）", evening: "平日晚上（詳細時間另行確認）" };
const statusLabels = { confirmed: "已確認", needs_information: "需要補充資料", rejected: "暫時無法安排" };
const result = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json; charset=UTF-8" } });
const trim = (value, size) => typeof value === "string" ? value.trim().slice(0, size) : "";
function cors(request, env) { const origin = request.headers.get("Origin") || ""; return (env.ALLOWED_ORIGINS || "").split(",").map(x => x.trim()).includes(origin) ? { "access-control-allow-origin": origin, "access-control-allow-methods": "GET, POST, PATCH, OPTIONS", "access-control-allow-headers": "authorization, content-type", vary: "Origin" } : {}; }
function respond(response, headers) { const merged = new Headers(response.headers); Object.entries(headers).forEach(([key, value]) => merged.set(key, value)); return new Response(response.body, { status: response.status, headers: merged }); }
function today() { const parts = new Intl.DateTimeFormat("en", { timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const get = type => parts.find(part => part.type === type).value; return `${get("year")}-${get("month")}-${get("day")}`; }
function validDate(value) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return null; const [y,m,d] = value.split("-").map(Number); const date = new Date(Date.UTC(y,m-1,d)); return date.getUTCFullYear() === y && date.getUTCMonth() === m-1 && date.getUTCDate() === d ? date : null; }
function validRule(service, value) { const date = validDate(value); if (!date || value < today()) return false; return service === "transfer" ? [0,3,6,9].includes(date.getUTCMonth()) && date.getUTCDay() === 0 && date.getUTCDate() <= 7 : service === "numerology"; }
async function user(request, env, admin = false) { const token = (request.headers.get("Authorization") || "").replace(/^Bearer\s+/, ""); if (!token) { console.log("line-auth:no-access-token"); return null; } const verifyUrl = new URL("https://api.line.me/oauth2/v2.1/verify"); verifyUrl.searchParams.set("access_token", token); const verified = await fetch(verifyUrl); if (!verified.ok) { console.log(`line-auth:verify-failed:${verified.status}`); return null; } const verification = await verified.json(); if (String(verification.client_id) !== String(env.LINE_MINI_APP_CHANNEL_ID)) { console.log("line-auth:channel-id-mismatch"); return null; } const profile = await fetch("https://api.line.me/v2/profile", { headers: { Authorization: `Bearer ${token}` } }); if (!profile.ok) { console.log(`line-auth:profile-failed:${profile.status}`); return null; } const data = await profile.json(); if (admin && data.userId !== env.ADMIN_LINE_USER_ID) { console.log("line-auth:not-admin"); return null; } return data; }
async function push(env, to, text) { if (!env.LINE_MESSAGING_CHANNEL_ACCESS_TOKEN || !to) return; const response = await fetch("https://api.line.me/v2/bot/message/push", { method: "POST", headers: { "content-type": "application/json", Authorization: `Bearer ${env.LINE_MESSAGING_CHANNEL_ACCESS_TOKEN}` }, body: JSON.stringify({ to, messages: [{ type: "text", text }] }) }); if (!response.ok) throw new Error(`LINE Push ${response.status}`); }
function customerText(booking) { return [`【預約${statusLabels[booking.status]}】`, `${booking.service_name}｜${booking.booking_date}｜${slots[booking.time_slot]}`, booking.status === "confirmed" ? "您的預約申請已確認。" : "我們已查看您的預約申請。", booking.admin_note ? `說明：${booking.admin_note}` : ""].filter(Boolean).join("\n"); }
export default { async fetch(request, env, ctx) { const headers = cors(request, env); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers }); const url = new URL(request.url); try { let response;
  if (request.method === "GET" && url.pathname === "/health") response = result({ ok: true });
  else if (request.method === "POST" && url.pathname === "/bookings") { const profile = await user(request, env); if (!profile) response = result({ error: "LINE 身分驗證失敗，請從 MINI App 重新開啟。" }, 401); else { const body = await request.json(); const serviceId=trim(body.service,30), bookingDate=trim(body.date,10), timeSlot=trim(body.time,30), customerName=trim(body.name,60), customerPhone=trim(body.phone,30), customerNote=trim(body.note,500), service=services[serviceId]; if (!service || !validRule(serviceId,bookingDate) || !service.slots.includes(timeSlot) || !customerName || !customerPhone || body.privacy !== "on") response=result({error:"預約資料不完整或不符合可預約規則。"},400); else { const now=new Date().toISOString(), booking={id:crypto.randomUUID(),line_user_id:profile.userId,customer_name:customerName,customer_phone:customerPhone,service_id:serviceId,service_name:service.name,booking_date:bookingDate,time_slot:timeSlot,customer_note:customerNote,status:"pending",admin_note:"",created_at:now,updated_at:now}; await env.DB.prepare("INSERT INTO bookings (id,line_user_id,customer_name,customer_phone,service_id,service_name,booking_date,time_slot,customer_note,status,admin_note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(booking.id,booking.line_user_id,booking.customer_name,booking.customer_phone,booking.service_id,booking.service_name,booking.booking_date,booking.time_slot,booking.customer_note,booking.status,booking.admin_note,now,now).run(); ctx.waitUntil(push(env,env.ADMIN_LINE_USER_ID,["【新的預約申請】",`${booking.service_name}｜${booking.booking_date}｜${slots[booking.time_slot]}`,`姓名：${booking.customer_name}`,`電話：${booking.customer_phone}`,booking.customer_note ? `備註：${booking.customer_note}` : "","請至管理後台確認。"].filter(Boolean).join("\n")).catch(console.error)); response=result({booking:{id:booking.id,status:booking.status}},201); } } }
  else if (request.method === "GET" && url.pathname === "/bookings") { if (!await user(request,env,true)) response=result({error:"沒有管理權限。"},403); else { const status=url.searchParams.get("status") || "pending", date=url.searchParams.get("date") || ""; if (!["pending","confirmed","needs_information","rejected","all"].includes(status) || (date && !validDate(date))) response=result({error:"無效的篩選條件。"},400); else { const where=[], params=[]; if(status!=="all"){where.push("status=?");params.push(status);} if(date){where.push("booking_date=?");params.push(date);} const rows=await env.DB.prepare(`SELECT * FROM bookings ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY booking_date, created_at`).bind(...params).all(); response=result({bookings:rows.results||[]}); } } }
  else if (request.method === "PATCH" && /^\/bookings\/[\w-]+$/.test(url.pathname)) { if (!await user(request,env,true)) response=result({error:"沒有管理權限。"},403); else { const body=await request.json(), status=trim(body.status,30), adminNote=trim(body.admin_note,500), id=url.pathname.split("/").at(-1); if(!Object.hasOwn(statusLabels,status)) response=result({error:"無效的預約狀態。"},400); else { const booking=await env.DB.prepare("SELECT * FROM bookings WHERE id=?").bind(id).first(); if(!booking) response=result({error:"找不到預約。"},404); else { const updated_at=new Date().toISOString(); await env.DB.prepare("UPDATE bookings SET status=?,admin_note=?,updated_at=? WHERE id=?").bind(status,adminNote,updated_at,id).run(); const updated={...booking,status,admin_note:adminNote,updated_at}; ctx.waitUntil(push(env,updated.line_user_id,customerText(updated)).catch(console.error)); response=result({booking:updated}); } } } }
  else response=result({error:"找不到 API 路徑。"},404); return respond(response,headers);
} catch (error) { console.error(error); return respond(result({error:"系統暫時無法處理，請稍後再試。"},500),headers); } } };
